### PR TITLE
Version 2.1.1

### PR DESCRIPTION
**Pull request by michaeldegroot**
#  New in version 2.1.1 :rocket:
#### Disconnect function added

```javascript
mysql.connectAsync().then(connected => {
    if (connected) {
        mysql.disconnectAsync().then(() => {
            // Now fully disconnected from mysql
        }).catch(err => {
            console.error('Could not disconnect:', err)
        })
    }
}).catch(err => {
    console.error('Could not connect:', err)
})
```
#### xxhash added
A new hashing algorithm for cache keys as been added to choose from, xxhash:
https://cyan4973.github.io/xxHash/

#### Farmhash added
Now the default hashing algorithm for cache keys (hashfarm64), Very fast!
https://github.com/lovell/farmhash

#### Benchmarks fixed
cacheProvider module was also being cached, resulting in wrong benchmark tests!

#### dbQuery event added

```javascript
mysql.event.on('dbQuery', info => {
    console.log('Mysql call has been fired', info)
})
```

*Called when a sql query was fired to the mysql database, as apposed to the query event; which is before the pre-cache check*

### CODE REVIEW

**Comment by p0d3r** [comment]
If we can figure out a way to map query hashes to custom names it would be cool. For example one may want to assign a custom key for a query then request for a cache refresh outside of its scope.

**Comment by michaeldegroot** [comment]
If I understand you correctly:

1. You create a mysql query and call it via mysql-cache
2. With this call you supply a 'zone' string
3. You can assign multiple queries to the same 'zone' string
4. You can at any point clear all the caches or do a bunch of other stuff with these zones by calling the zone name

**Comment by p0d3r** [comment]
Well i did not meant that but you just created a new perfect idea, lol!

What I was trying to say is, for example,

- I have two queries which selects and updates. Like: `SELECT * FROM users WHERE id = 1` and I set custom hash to `GET_USER_QUERY_FOR_ID_**1**` (1 here is dynamic, i can set with variable like req.session.user_data.id)

- And the other query for updating that user, `UPDATE users SET credits = credits + 200 WHERE id = 1` and then I want to refresh the cache for `GET_USER_QUERY_FOR_ID_1`

- Now there is two things I can do: first I can set a variable to user's session like `req.session.refresh_userdata_on_next_query` to `true` and pass it to `refreshCache` option then set it to `false`, or tell mysql-cache to `refreshCache` for hash `GET_USER_QUERY_FOR_ID_1`

**Comment by p0d3r** [comment]
Or may be a smart system that checks for tables and conditions after where on insert and update queries that identifies if next select query which has that table and condition**(s)** be refreshed on next call.

**Comment by michaeldegroot** [comment]
Seems like you could fix your problem with this new 'zone' thing :)

1 Call a query `SELECT * FROM users WHERE id = 1`
2. set the zone to `USER_CREDITS_**1**` when calling this query
3. after each update call (or a when you update the user credits w/e), use a clear cache zone function to clear all caches with the zone name `USER_CREDITS_**1**`
4. When  `SELECT * FROM users WHERE id = 1` is called again it will be retrieved from database because zone was cleared.

This smart system also sounds very cool, I will consider it if I don't get too many head bashes on the table  hehe.

**Comment by p0d3r** [comment]
This is perfect and it will save way too much implementation cost for me :)

**Pull request merged**
